# Generated by Django 3.2.6 on 2021-08-05 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0004_blog_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='blogs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialnetwork.blog'),
        ),
    ]
