# Generated by Django 3.2.6 on 2021-08-07 11:31

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialnetwork', '0005_subscription_blogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='blogs',
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='socialnetwork.blog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='blog',
            field=models.ManyToManyField(to='socialnetwork.Blog'),
        ),
    ]
